### PR TITLE
Add SHA to list of tokens

### PR DESCRIPTION
**Pull request by dylanabaker**
This PR allows using the commit SHA in the format string. I opted for the short version because it looks a little more friendly and occupies less screen real estate.

### CODE REVIEW

**Comment by gregorym** [comment]
Can you add a screenshot so i can see before/after?

**Comment by dylanabaker** [comment]
Before:

before

After:

screenshot

**Comment by gregorym** [comment]
Thanks for your contribution!

**Comment by dylanabaker** [comment]
Thank you as well! Cheers

**Pull request merged**
